# This Makefile is generated by omake: https://github.com/ouonline/omake.git

AR := ar
CC := gcc

ifeq ($(debug), y)
	CFLAGS := -g
else
	CFLAGS := -O2 -DNDEBUG
endif
CFLAGS := $(CFLAGS) -Wall -Werror -Wextra -fPIC

TARGET := liblogger.a liblogger.so

.PHONY: all clean

all: $(TARGET)

.PHONY: __omake_dep__1

__omake_dep__1:
	$(MAKE) debug=$(debug) libutils.a -C ../utils

logger_OBJS := file_logger.c.logger.o stdio_logger.c.logger.o

logger_INCLUDE := -I..

logger_LIBS := ../utils/libutils.a -lpthread

file_logger.c.logger.o: file_logger.c
	$(CC) $(CFLAGS) $(logger_INCLUDE) -c $< -o $@

stdio_logger.c.logger.o: stdio_logger.c
	$(CC) $(CFLAGS) $(logger_INCLUDE) -c $< -o $@

liblogger.a: $(logger_OBJS) | __omake_dep__1
	$(AR) rc $@ $^

liblogger.so: $(logger_OBJS) | __omake_dep__1
	$(CC) -shared -o $@ $^ $(logger_LIBS)

clean:
	rm -f $(TARGET) $(logger_OBJS)
